swagger: '2.0'
info:
  title: My API
  version: '1.0'
paths:
  /api/users:
    get:
      summary: Returns a list of users
      responses:
        200:
          description: A list of users
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
    post:
      summary: Creates a new user
      parameters:
        - name: user
          in: body
          required: true
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
      responses:
        201:
          description: User created
          schema:
            type: object
